import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:flutter/foundation.dart';
import '../../firebase_options.dart'; // Auto-generated by FlutterFire CLI

/// Firebase initialization service
class FirebaseService {
  static Future<void> initialize() async {
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      debugPrint('✅ Firebase initialized successfully');
      
      // Initialize App Check
      await _initializeAppCheck();
    } catch (e) {
      debugPrint('❌ Firebase initialization error: $e');
      rethrow;
    }
  }
  
  static Future<void> _initializeAppCheck() async {
    try {
      await FirebaseAppCheck.instance.activate(
        // Use debug provider in debug mode, device check/play integrity in release
        androidProvider: kDebugMode 
            ? AndroidProvider.debug 
            : AndroidProvider.playIntegrity,
        appleProvider: kDebugMode 
            ? AppleProvider.debug 
            : AppleProvider.deviceCheck,
      );
      debugPrint('✅ Firebase App Check initialized successfully');
    } catch (e) {
      debugPrint('⚠️ App Check initialization warning: $e');
      // Don't rethrow - App Check is optional and shouldn't block app startup
    }
  }
}

